### ISSUE TITLE
Anchor of value (not an entire object) doesn't work?

### ISSUE THREAD

**Issue by spordin** [FasterXML/jackson-dataformat-yaml#62]
Is this a bug, or am I missing some kind of mapping annotation?

``` java
import static org.junit.Assert.*;

import java.io.IOException;
import org.junit.Test;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;

public class YamlParserTest {
    private ObjectMapper objectMapper = new ObjectMapper(new YAMLFactory());

    public static class Test1 {
        private Long value1;
        private Long value2;

        public Long getValue1() {
            return value1;
        }
        public void setValue1(Long value1) {
            this.value1 = value1;
        }
        public Long getValue2() {
            return value2;
        }
        public void setValue2(Long value2) {
            this.value2 = value2;
        }
    }

    @Test
    public void test() throws IOException {
        String yaml =
        "value1: &test_1 123\n" +
        "value2: *test_1";
        Test1 test1 = objectMapper.readValue(yaml, Test1.class);
        assertEquals(123L, test1.getValue1().longValue());
        assertEquals(123L, test1.getValue2().longValue());
    }

}
```

The associated stacktrace:

```
com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of long from String value 'test_1': not a valid Long value
 at [Source: java.io.StringReader@4923ab24; line: 2, column: 9] (through reference chain: Test1["value2"])
    at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:55)
    at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:883)
    at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseLong(StdDeserializer.java:454)
    at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:321)
    at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:303)
    at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523)
    at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
    at com.fasterxml.jackson.databind.deser.impl.BeanPropertyMap._findDeserializeAndSet2(BeanPropertyMap.java:313)
    at com.fasterxml.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:291)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:248)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3564)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2580)
    at YamlParserTest.test(YamlParserTest.java:36)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by cowtowncoder** [comment]
Anchors will only work the way Jackson Object Ids work: that is, referenced type MUST have `@JsonIdentityInfo` annotation. Type `java.lang.Long` may not be referenced that way, although it would be possible to create a simple wrapper object that could be reference.
So usage as indicated by test is not supported.

Error handling for this case should probably work better to give more meaningful error message.

**Comment by spordin** [comment]
Thank you for the response. So if I'm understanding correctly, my test case is not a bug, but a yaml feature that is not supported and there are no plans to add that support?

**Comment by spordin** [comment]
My simple example works if I use the underlying yaml parser directly, which should be sufficient for my needs. But this seems like a pretty big feature to not support.

```@Test
    public void testSnakeYaml() throws IOException {
        Test1 test1 = new Yaml().loadAs(YAML, Test1.class);
        assertEquals(123L, test1.getValue1().longValue());
        assertEquals(123L, test1.getValue2().longValue());
    }```

**Comment by cowtowncoder** [comment]
@spordin Hmmh. Was about to say that you are right, but now that I think about it, I wonder if it actually might work... since annotation may be added to field. So something like:

```java
public static class Test1 {
       @JsonIdentityInfo(generator=ObjectIdGenerators.IntSequenceGenerator.class, property="id")
       private Long value1;
       @JsonIdentityInfo(generator=ObjectIdGenerators.IntSequenceGenerator.class, property="id")
       private Long value2;
}
```

which would indicate that id is to be used.

The trick is that general support for object references does not and will not work; but for types or properties that indicate use of object id, reference, it may actually work.
I have not tested this with non-POJO types, but given that YAML has construct, this actually just might work.

**Comment by spordin** [comment]
@cowtowncoder unfortunately that doesn't seem to fix it. I still get the same Exception.

**Comment by cowtowncoder** [comment]
Actually, no, this does not and will not work as-is, since Object Identity only works for structured objects like POJOs (beans). It is not designed to work for scalars like `int`, `long` or `java.lang.String`s.

Now: it is possible to change things such that a POJO is represented as JSON/YAML Scalar, like integral number, but unfortunately this is unlikely to work either since then it becomes difficult if not impossible to detect difference between object reference ("anchor" in YAML) and full object serialization.

**Comment by cowtowncoder** [comment]
Moved: https://github.com/FasterXML/jackson-dataformats-text/issues/6
