### ISSUE TITLE
Problem to parse time values as string

### ISSUE THREAD

**Issue by heroldus** [FasterXML/jackson-dataformat-yaml#69]
There is a problem with parsing time values as string. You can simply test the behavior with:
```java
ObjectMapper mapper = new ObjectMapper(new YAMLFactory());
mapper.readValue("value: 3:00", JsonNode.class);
```
It produces:
```
com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input when binding data into ObjectNode
 at [Source: java.io.StringReader@2a742aa2; line: 1, column: 8]

	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:261)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:1277)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:226)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:70)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:16)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2833)
	at com.scout24.data.aws.pipeline.YamlStringTest.testYamlTimeValue(YamlStringTest.java:14)
```

The problem is that SnakeYAML resolves the value `3:00` as `Tag.INT` in `YAMLParser:448` but `_decodeNumberScalar` is not able to parse the value. I'm no YAML expert, but my expectation would be that `3:00` is intepreted as string value.

**Comment by cowtowncoder** [comment]
@heroldus thank you for reporting this. I don't know YAML syntax by heart either, and am bit surprised to find "3:00" anything other than String.... I hope this one is easier to tackle; most likely unknown event is discarded and state machine produces wrong logical `JsonToken`, missing `END_OBJECT` and thereby leading to exception being observed.

**Comment by christiandietze** [comment]
It may be interesting to know that writing the time in `HH:MM` format works, as does quoting it.

```
ObjectMapper mapper = new ObjectMapper(new YAMLFactory());
mapper.readValue("value: 03:00", JsonNode.class);
```
